Update Table of contents and Command summary for UG
AY2223S2-CS2103T-T12-1/tp pull request #138
Opened 2023-03-30 15:22 UTC by jinnieshin

Adds Table of Contents with hyperlinks
Updates Command summary to match the current features Adds FAQ

2023-03-30 16:12 UTC, lukkesreysandeur requested changes

2023-03-30 16:13 UTC, jinnieshin commented on docs/UserGuide.md
> +| Action                                                                                                        | Format, Examples
Wouldn't that be too lengthy for a summary..?

2023-03-30 16:13 UTC, jinnieshin commented on docs/UserGuide.md
> -{:toc}
Ok

2023-03-30 16:16 UTC, lukkesreysandeur commented on docs/UserGuide.md
> +| Action                                                                                                        | Format, Examples
Maybe we can split it into 3 columns instead? One for the example and one for the format.

2023-03-30 18:15 UTC, lukkesreysandeur commented on docs/UserGuide.md
> +* Table of Contents {:toc}
Actually this line still doesn't generate the table correctly, the {:toc} should be on the next line.

2023-03-31 00:19 UTC, euph00 approved these changes
I will make the requested changes on my end

2023-03-31 00:19 UTC, merged